### ISSUE TITLE
REP問題

### ISSUE THREAD

**Issue by gue0857** [Gaduo/IHE-Technical-Frameworks.tcumi#3]
簡工程師您好:
假如我要將資料儲存於不同的REP，但是有一個集中的REG，我該怎麼做?
1.如何架設新的REP以及設定所有分散的REP導向同一個REG
2.不同REP之下，呼叫同一個服務“ /base/ProvideAndRegisterDocumentSet/” 上傳嗎?
3.進行索引查詢時，因我是統一的REG，所以呼叫“/base/RegistryStoredQuery/”和“/base/RetrieveDocumentSet/”是不變的，對吧?

**Comment by Gaduo** [comment]
1. 部分資訊寫在[這裡](http://gaduo.github.io/IHE-Technical-Frameworks.tcumi/devenvironment.openxds#top)，還有一些設定沒有補上。
1. 對，呼叫 ProvideAndRegisterDocumentSet 但要指定傳給哪個 repository
1. 向同一個 Registry 查詢 metadata，但要剖析  repositoryUniqueId 對應的  repository，再分批調回分散於不同 repository 的文件。

**Comment by gue0857** [comment]
2.指定傳給哪個 repository->是如何指定?在範例中只上傳METADATA至/base/ProvideAndRegisterDocumentSet/，不知道如何指定

**Comment by Gaduo** [comment]
@gue0857 
另開一個 issue #4
