### ISSUE TITLE
資料儲存問題

### ISSUE THREAD

**Issue by gue0857** [Gaduo/IHE-Technical-Frameworks.tcumi#6]
你好:)
請問一下，假設我有一份門診病歷，一份用藥紀錄，放在同一個REP，調閱文件時，我要怎麼判斷他是哪一份文件?是將DOCUMENT UID建立規則，再去判斷嗎?還是有其他的方法可以分辨文件，THX

**Comment by gue0857** [comment]
還是我再創立文件的名稱上，做分別?RegistryStoredQuery 回來以後去判斷檔名

**Comment by Gaduo** [comment]
可以註記在 `Classification` 中。
至於是哪一種，可以到這 http://gaduo.github.io/IHE-Technical-Frameworks.tcumi/affinitydomain#top 查詢。
關鍵字：outpatient (門診)、medication、medicine (藥物)。

執行 ITI-18時，可以透過參數-classification + patient Id，精確的查詢你要的文件分類。

**Comment by Gaduo** [comment]
可以在 metadata 註記 `classification` (分類)，如下圖所示。
至於要用哪一種可以在這 http://gaduo.github.io/IHE-Technical-Frameworks.tcumi/affinitydomain#top 查詢。
關鍵字：outpatient、medicine、medication。
若沒有精確的分類，則要 `自定義` ，但要公告給整個 XDS 用戶。

![124](https://cloud.githubusercontent.com/assets/5178062/15624738/eff5cf80-24c2-11e6-85c0-5966735b2d93.png)

PS
---
Github issue 留言區塊右上方有修改紐，同一件事情放在一起說明。

**Comment by gue0857** [comment]
我在 ITI-18 增加這個嗎? $XDSDocumentEntryHealthcareFacilityTypeCodeScheme : XXXX
就能找到 METADATA中 healthcareFacilityTypeCode = XXXX 的文件?

**Comment by Gaduo** [comment]
對，沒錯。
你可以實驗看看。

**Comment by gue0857** [comment]
我試了 "$XDSDocumentEntryHealthcareFacilityTypeCodeScheme": 281PC2000N 失敗的
是格式有錯嗎?

**Comment by Gaduo** [comment]
格式
====
```
{
  "uuid": "urn:uuid:14d4debf-8f97-4251-9a74-a90016b0af0d",
  "returnType": "ObjectRef",
  "parameter": {
    "$XDSDocumentEntryPatientId": "bb74071cffbc41d^^^&1.3.6.1.4.1.21367.2005.13.20.2000&ISO"
  },
  "parameters": {
    "$XDSDocumentEntryStatus": [
      "urn:oasis:names:tc:ebxml-regrep:StatusType:Approved"
    ],
    "$XDSDocumentEntryHealthcareFacilityTypeCode": [
      "XXXX"
    ]
  }
}
```

**Comment by gue0857** [comment]
成功 THX!
