### ISSUE TITLE
搜尋條件問題

### ISSUE THREAD

**Issue by gue0857** [Gaduo/IHE-Technical-Frameworks.tcumi#8]
你好~
我現在可以用XDSDocumentEntryCreationTimeFrom/To、$XDSDocumentEntryPatientId、XDSDocumentEntryHealthcareFacilityTypeCodeScheme來搜尋要得文件

authorInstitution/authorPerson/authorSpecialty(醫院/醫生/科別) 我該用什麼條件去搜尋?
$XDSDocumentEntryAuthorPerson 嗎?
ITI-18的格式該怎麼寫?
或者我ITI-18調閱回來LeafClass，再去解析內容判斷
THX

**Comment by Gaduo** [comment]
1. 可以參考 ITI-TF-Vol2a 3.18Registry Stored Query，以了解有那些搜尋參數。
1. 至於 AuthorPerson 是新定義的搜尋參數，目前我使用的 openxds 版本沒有更新這項功能。

參考
===
http://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_TF_Vol2a.pdf
